[package]
name = "erc20"
version = "0.1.0"
authors = ["Rodolfo Araujo <rodoufu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0"
serde = "1.0"
web3 = "0.10"
